######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 28 19:05:46 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += AddCourse.h DeleteCourse.h mainWindow.h MessageWindow.h
SOURCES += AddCourse.cc DeleteCourse.cc main.cc mainWindow.cc MessageWindow.cc
