######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 28 09:39:07 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += AddCourse.h mainWindow.h
SOURCES += AddCourse.cc main.cc mainWindow.cc
